### ISSUE TITLE
xml file not finding my UIViewController ?

### ISSUE THREAD

**Issue by mrwcjoughin** [schibsted/layout#36]
Despite having code exactly like the SampleApp, if I use my view controllers name in my xml file i get the red error in the simulator saying it can't find my view controller ?
But if i use UIViewController in the xml file it does find it ?
I have checked and rechecked and everything is spelt correctly, and everything has the right access modifier, but no matter what i do it can't find my viewcontroller.

I am using 0.4.14 via cocoapods

**Comment by mkarp** [comment]
It would be helpful if you publish your test project publicly so we can have a look.

**Comment by mrwcjoughin** [comment]
here it is:
https://github.com/AdaptableApps/grobinson-styler-ios.git

its on the **dev** branch

**Comment by nicklockwood** [comment]
@mrwcjoughin it's because the app name "grobinson-styler-ios" is not a valid module name, and Layout doesn't correctly demangle it to "grobinson_styler_ios" (with underscores), which is what Swift uses for the module.

I'll try to fix this, but in the meantime you can make it work by using an explicit module namespace for all your custom classes in your XML, e.g.:

```xml
<grobinson_styler_ios.StylerViewController/>
```

**Comment by mrwcjoughin** [comment]
@nicklockwood aah, awesome, thanks that works. much appreciated

**Comment by nicklockwood** [comment]
Fixed in 0.4.17
