### ISSUE TITLE
Just some questions to your plans on this library.

### ISSUE THREAD

**Issue by patchthecode** [schibsted/layout#42]
1. Do you have any plans for this to work with Android?
2. I like the concept of react native, but there were a number of reasons i didn't go with it. Does this library basically provides the same advantage of reactive native for iOS?
3. Is this library already being used any where in production?

I just thought the idea for a declarative framework for UI (apart from reactive native) was a good idea. And I just wanted the questions answered so I get a bit more assurance in using this framework on a larger project.

**Comment by nicklockwood** [comment]
> Do you have any plans for this to work with Android?

Not in the near future. An Android port would need to be a written more-or-less from scratch since Layout is written in Swift. Also, Android's built-in XML-based layout system already has many of the advantages that Layout brings to iOS.

> I like the concept of react native, but there were a number of reasons i didn't go with it. Does this library basically provides the same advantage of reactive native for iOS?

It provides many of the advantages, such as declarative data binding, human-readable layout code, live reloading of UI changes. It doesn't offer cross-platform UI or over-the-air business logic updates.

> Is this library already being used any where in production?

Yes, Schibsted has a suite of apps on the App Store that are using Layout, though none are available in English currently: https://itunes.apple.com/gr/developer/schibsted-media-group/id1043471023

**Comment by patchthecode** [comment]
Understood. It looks great.
closing this issue.
As I am just experimenting with this library. Expect some noobish questions on some layouts ok. 
I'll open a git repository so that i can experiment with somethings, and i'll base the questions i'll ask on that repository. Have a good one.
