### ISSUE TITLE
Independent views in XML

### ISSUE THREAD

**Issue by comm1x** [schibsted/layout#49]
First I would like to express my **great gratitude** for this project. I'm sure it has a huge perspectives and it will become very popular tool.

Right now we can split big layouts on parts using `xml="view.xml"` syntax and reuse parts. But we can't build and import whole independent views. When we importing parts, outlets of parts binds to current viewcontroller. And if we reuse part in another viewcontroller, we are forced to duplicate all outlets. And this is not good.

Our syntax `xml="View.xml"` is an alternative of `<include layout="view.xml"/>` in Android.
But more powerful and useful approach `<my.own.Toolbar/>` is missing.

_PS May be it is possible, and I didn't understand how to do this._

**Comment by nicklockwood** [comment]
There are two different concepts of a custom view in xml:

* You can create an xml file that configures an existing UIView class with a given set of properties, etc. 
* You can subclass UIView in Swift and then reference your custom view class in a Layout xml

In the former case, you would load your xml file like this:

```xml
<UIView xml="MyView.xml" someAttribute="foo" />
```

In the latter case, you'd just reference your custom view directly.

```xml
<MyCustomView someAttribute="foo" />
```

If I understand correctly, you are talking about a 3rd case, where you want to define a custom View in code, but also configure it using XML. In this case, you would want the view to have "baked into it" the knowledge of which XML file it needs to load.

This is possible, although it's not especially straightforward at the moment. The thing to understand is that when you reference MyCustomView in XML, Layout doesn't know or care whether MyCustomView itself is using Layout for its own configuration. MyCustomView is a black box, and it could be getting its own subviews using code, a nib file, xml or anything else.

To create a custom view that configures its own content using Layout, you would do something like this:

```swift
class MyCustomView: UIView, LayoutLoading {
    override func init(frame: CGRect) {
        super.init(frame: frame)
        loadLayout(named: "MyCustomView.xml")
    }
}
```

This view will now load whatever is inside MyCustomView.xml and add it *as a subview* to itself. That means the root node in "MyCustomView.xml" should *not* itself be an instance of MyCustomView. MyCustomView in this case is the *owner* of the Layout, not the element defined in the Layout.

If you have outlets defined in MyCustomView.xml, they will be bound to MyCustomView, not its parent view controller.

Since MyCustomView is an ordinary UIView from an external perspective, it can be used in any way that you would use a normal view - including using it inside another Layout XML file.

Hope that helps!

**Comment by comm1x** [comment]
Thank you for your answer, Nick.
I am tried again, and it did not work.

I define simple custom view `Custom Label` with code:
```
class CustomLabel: UIView, LayoutLoading {
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        loadLayout(named: "CustomLabel.xml")
    }
    override init(frame: CGRect) {
        super.init(frame: frame)-
        loadLayout(named: "CustomLabel.xml")
    }
}
```
and `CustomLabel.xml` layout:
```
<UILabel
    width="100%"
    height="100%"
    text="Custom Label 4"/>
```

Then, I declare container and try to use inside it:

```
<UIView
        outlet="container"
        top="100"
        width="100"
        height="100"
        backgroundColor="#ff0">
        <UILabel text="Default Label"/>
        <CustomLabel/>
</UIView>
```

And I see this:
![Screenshot](https://i.gyazo.com/65606fa3c1762471a29d2d99c65049d4.png)

Default `UILabel` rendered, but `CustomLabel` not rendered.
Version of Layout 0.4.20

**Comment by nicklockwood** [comment]
Sorry, I forgot you need to include this in your CustomLabel, or your Layout won't update to match fit the container size when it changes:

    override func layoutSubviews() {
        layoutNode?.update()
    }

**Comment by comm1x** [comment]
Yeah, it works! Very nice! :) 
I think it would be good to write about it in README.

**Comment by nicklockwood** [comment]
It's mentioned in the Advanced topics section, but the docs could be clearer.

**Comment by nicklockwood** [comment]
I've improved the docs for this in the README.
